export const HANDLE_ACTION = 'HANDLE_ACTION';
export const ADD_NEW_PRODUCT_SUCCESS = 'ADD_NEW_PRODUCT_SUCCESS';
export const CHANGE_PRODUCTS_ACTIONS_FIELD = 'CHANGE_PRODUCTS_ACTIONS_FIELD';
export const GET_ONE_PRODUCT = 'GET_ONE_PRODUCT';
export const SET_START_PRODUCT_DATA = 'SET_START_PRODUCT_DATA';
export const CLEAN_PRODUCTS_ACTIONS = 'CLEAN_PRODUCTS_ACTIONS';
